customhost = "employee.c9axgcjhwh1z.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "cheongtecksing-employee"
customregion = "us-east-1"
